top_srcdir   = /compilation/httpd-2.4.4
top_builddir = /compilation/httpd-2.4.4
srcdir       = /compilation/httpd-2.4.4/server/mpm/worker
builddir     = /compilation/httpd-2.4.4/server/mpm/worker
VPATH        = /compilation/httpd-2.4.4/server/mpm/worker

include $(top_srcdir)/build/special.mk
