#!/bin/sh

export TERMINFO=/hdd/server/etc/terminfo
export TERM=pcansi
export LYNX_CFG=/hdd/server/lynx/etc/lynx.cfg
export LYNX_LSS=/hdd/server/lynx/etc/lynx.lss
export TMPDIR=/hdd/server/lynx/cache

/hdd/server/lynx/lynx
