#!/system/bin/sh

export TERMINFO=/system/etc/terminfo
export TERM=pcansi
export LYNX_CFG=/androidserver/lynx/lynx.cfg
export LYNX_LSS=/androidserver/lynx/lynx.lss
export TMPDIR=/androidserver/lynx/cache

/androidserver/lynx/lynx
