/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 ../../../miniperl ../bin/enc2xs -Q -o ma_03_t.c -f ma_03_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t MacChineseTrad_encoding;
