/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 ../../../miniperl ../bin/enc2xs -Q -o eu_01_t.c -f eu_01_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t euc_kr_encoding;
