/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 ../../../miniperl ../bin/enc2xs -Q -o ks_03_t.c -f ks_03_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t ksc5601_raw_encoding;
